// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://deftuemtjmecwrdmvzeo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRlZnR1ZW10am1lY3dyZG12emVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA1NzQ2NjMsImV4cCI6MjA1NjE1MDY2M30.m6xW6mklc-214Dqq3iXhyYygifxkYFnTp-69BbVFnf4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});